//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCRUD.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgramacaoWebEntities : DbContext
    {
        public ProgramacaoWebEntities()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BAIRRO> TB_BAIRRO { get; set; }
        public virtual DbSet<TB_EMPRESA> TB_EMPRESA { get; set; }
        public virtual DbSet<TB_MUNICIPIO> TB_MUNICIPIO { get; set; }
        public virtual DbSet<TB_PERFIL> TB_PERFIL { get; set; }
        public virtual DbSet<TB_UF> TB_UF { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
