//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCRUD.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EMPRESA()
        {
            this.TB_USUARIO = new HashSet<TB_USUARIO>();
        }
    
        public int emp_id { get; set; }
        public string emp_nm_fantasia { get; set; }
        public string emp_logradouro { get; set; }
        public string emp_complemento { get; set; }
        public int emp_brr_codigo { get; set; }
        public int emp_mnp_codigo_ibge { get; set; }
        public int emp_uf_codigo { get; set; }
        public string emp_cep { get; set; }
        public string usr_telefone { get; set; }
        public System.DateTime emp_dt_cadastro { get; set; }
        public System.DateTime emp_dt_atualizacao { get; set; }
        public bool emp_deletado { get; set; }
    
        public virtual TB_BAIRRO TB_BAIRRO { get; set; }
        public virtual TB_MUNICIPIO TB_MUNICIPIO { get; set; }
        public virtual TB_UF TB_UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
