//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCRUD.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PERFIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PERFIL()
        {
            this.TB_USUARIO = new HashSet<TB_USUARIO>();
        }
    
        public int pfl_id { get; set; }
        public string pfl_nome { get; set; }
        public string pfl_descricao { get; set; }
        public System.DateTime pfl_dt_cadastro { get; set; }
        public System.DateTime pfl_dt_atualizacao { get; set; }
        public bool pfl_deletado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
