//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCRUD.Infrastructure
{
    using System;
    using System.Collections.Generic;

    public partial class TB_USUARIO
    {
        public int usr_id { get; set; }
        public string usr_nome { get; set; }
        public string usr_sexo { get; set; }
        public System.DateTime usr_dt_nascimento { get; set; }
        public string usr_cpf { get; set; }
        public string usr_telefone { get; set; }
        public string usr_email { get; set; }
        public string usr_senha { get; set; }
        public string usr_logradouro { get; set; }
        public string usr_complemento_logradouro { get; set; }
        public int brr_codigo { get; set; }
        public int mnp_codigo_ibge { get; set; }
        public string usr_cep { get; set; }
        public int uf_codigo { get; set; }
        public int emp_id { get; set; }
        public int pfl_id { get; set; }
        public System.DateTime usr_dt_cadastro { get; set; }
        public System.DateTime usr_dt_atualizacao { get; set; }
        public bool usr_deletado { get; set; }

        public virtual TB_BAIRRO TB_BAIRRO { get; set; }
        public virtual TB_EMPRESA TB_EMPRESA { get; set; }
        public virtual TB_MUNICIPIO TB_MUNICIPIO { get; set; }
        public virtual TB_PERFIL TB_PERFIL { get; set; }
        public virtual TB_UF TB_UF { get; set; }
    }
}
